### ISSUE TITLE
introduce SSE implementation for push notifications from server

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamClient#335]
Use https://github.com/mpetazzoni/sseclient,
which works with `requests` when it's called with `stream=True`
http://docs.python-requests.org/en/master/user/advanced/#streaming-requests

Prerequisite: 
- [x] make sure https://github.com/remy/polyfills work for SSE with Edge on Win10
- [x] implement switch to `requests` #14 

This invalidates #334

**Comment by loomis** [comment]
I've arbitrarily decided that the [amvtek](https://github.com/amvtek/EventSource) was the best one because it has tagged releases, is available in node.js through npm, and has a live test suite that passes on the Edge browser. I've included this in the WebUI `index.html`.  @konstan Feel free to change to a different implementation if you have problems with this one.
