### ISSUE TITLE
Bootscript should not re-downloaded python in component deployed from a built image

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamClient#375]
cf. https://support.sixsq.com/helpdesk/tickets/2411

**Comment by schaubl** [comment]
This is due to the way the build image works.

When building an image, the SlipStream agent is not installed in the VM.
The Orchestrator simply execute the build recipes on the VM via SSH.
So in this case the SlipStream agent and it's dependencies (like Python 2) are not downloaded.

To ensure Python 2 is in the built image, please add it into the list of packages to install during the build.
